server:
  port: 8085
  
spring:
  application:
    name: notification-service
    
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

# Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic  
    consumer:
      group-id: notificationId
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:io.com.notification.OrderPlacedEvent
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    
