server:
  port: 8082
  
spring:

  application:
    name: inventory-service
    
  cloud:
    config:
      import-check:
        enabled: false
        
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/inventoryService?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      max_allowed_packet: 2000
    show-sql: true


management:
  server:
    port: 8084
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
